name: Afinitude
favicon: null
layout_spectrum: 0.2772737245541066
typography_spectrum: 0.30367786483839154
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.15914572891779244
  lightness: 0.2679688052739948
  saturation: 0.35528190224431455
  rhythmicContrast: 0.5987781719304621
purpose: []
